events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx
                     levels=1:2
                     keys_zone=reports_cache:50m
                     max_size=10g
                     inactive=7d
                     use_temp_path=off;

    server {
        listen 80;
        server_name _;

        location /reports/ {
            proxy_pass http://minio:9000/bionicpro-reports/;

            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host minio:9000;

            proxy_hide_header    Set-Cookie;
            proxy_ignore_headers Set-Cookie;

            proxy_cache           reports_cache;
            proxy_cache_key       "$uri";
            proxy_cache_valid     200 24h;
            proxy_cache_valid     404 1m;
            proxy_cache_use_stale error timeout updating http_500;
            proxy_cache_lock      on;

            # Если клиент передаёт заголовок X-Purge: 1 - игнорируем кеш
            proxy_cache_bypass       $http_x_purge;
            proxy_no_cache           $http_x_purge;

            proxy_intercept_errors on;
            error_page 404         = @not_found;

            add_header Cache-Control "public, max-age=86400";
            add_header X-Cache-Status $upstream_cache_status;
        }

        location @not_found {
            return 404 '{"error":"Report not found"}';
            add_header Content-Type application/json;
        }
    }
}
